# version: "3"

services:
  backend:
    image: 
    container_name: 
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    env_file:
      - .env
    networks:
      - publication-network

networks:
  publication-network:
    name: publication-network
    driver: bridge
    external: true
