app:
  name: "Diengs ID Development Environment"
  port: "8001"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "publication_db"
  tz: "Asia/Jakarta"

s3:
  bucketName: storage-main
  region: us-east-1
  endpoint: https://is3.cloudhost.id
  accessKey: 6QAX2YLNIIQVYWV4TJSN
  secretKey: qpCP9Bt9INlDMlLZbdpLgPYuoqBHJRV5GmKPvQ58
